import type {
  BleDeviceInfo,
  CharacteristicBinding,
  ConnectionContext,
  ScaleAdapterCore,
  GattWiring,
  MultiCharNotify,
  ScaleReading,
  UserProfile,
  BodyComposition,
} from '../interfaces/scale-adapter.js';
import { uuid16, buildPayload } from './body-comp-helpers.js';
import { bleLog } from '../ble/types.js';
import { isHutbitOemAdvert } from './lefu-signature.js';
import type { MatchDescriptor } from './match-descriptor.js';

// ─── Robi S9 (Lefu / Fitdays FFB0-new protocol) ─────────────────────────────

const CHR_FFB1 = uuid16(0xffb1); // write (handshake)
const CHR_FFB2 = uuid16(0xffb2); // notify (live frames)
const CHR_FFB3 = uuid16(0xffb3); // indicate (final result) - see binding note

/**
 * Handshake: `B0` hello, then three `BA` frames. The frame bytes are a
 * verbatim capture (real Fitdays app session), replayed
 * with a stale timestamp on every connection.
 *
 * The `BA` trailer/checksum is generated by a native library (icomon's
 * `libICBleProtocol.so`, class `ICBleScaleNewProtocol`; confirmed via `jadx`
 * + `nm` on the Fitdays APK, not reverse engineerable from the Java/Kotlin
 * side), so it cannot be regenerated for a fresh timestamp. Verified on real
 * hardware that this does not matter: the scale accepts this exact byte
 * repeatedly, across separate connections; it does not check the embedded timestamp
 * for freshness. That makes a verbatim replay a legitimate permanent fix,
 * not just a stopgap: it unlocks BIA (impedance + heart rate) the same way
 * the #228-era static handshake unlocked weight-only, just with the correct frame family.
 */
function buildHandshake(): Buffer[] {
  return [
    Buffer.from('000300b073000000000000000000000000000003', 'hex'),
    Buffer.from('011000ba6a932cc7007800000000ac1770982f1c', 'hex'),
    Buffer.from('021000ba6a932cc7007800000000aa00009d2f18', 'hex'),
    Buffer.from('031000ba6a932cc7007800000000aa00009d2f18', 'hex'),
  ];
}


// Weight is stored as a 3-byte big-endian gram count in the A3 result frame
// (#248: 01 2d c2 = 77250 g = 77.25 kg). The earlier #228 guess treated the high
// gram bytes (01 2c..) as a constant prefix because both prior captures were
// ~77 kg; they are not constant, they are the weight.
const WEIGHT_OFFSET = 5;
const WEIGHT_BYTES = 3;
const WEIGHT_DIV = 1000;

/**
 * Adapter for the Robi S9 smart scale (Fitdays app, Lefu-style FFB0 protocol).
 *
 * Shares service 0xFFB0 with the openScale MGB family but speaks a different
 * 20-byte frame protocol (`[seq][len][00][type][payload][trailer]`): the phone
 * runs a `B0`/`BA` handshake on FFB1, the scale streams A2 live frames on FFB2
 * (notify) and the final result as an A3 frame on FFB3 (indicate). The MGB
 * adapter sent the wrong init and never subscribed FFB3, so the scale dropped
 * the link before any reading (#228).
 *
 * The weight scale is confirmed against a known-weight capture (#248).
 * Impedance/heart-rate are decoded and confirmed using a live Fitdays app session:
 * the tool's own A3 frames had previously come back all-zero after the weight,
 * traced to the old #228-era handshake using the wrong opcode (`B1`/`BD` instead of `BA`).
 * See `buildHandshake()`.
 */
export class RobiS9Adapter implements ScaleAdapterCore, GattWiring, MultiCharNotify {
  readonly name = 'Robi S9';
  readonly match: MatchDescriptor = {
    priority: 40,
    custom: true,
    names: { includes: ['robi'] },
    serviceUuids: ['ffb0'],
    charUuids: ['ffb3'],
  };
  // Legacy single-char fields (unused in multi-char mode).
  readonly charNotifyUuid = CHR_FFB2;
  readonly charWriteUuid = CHR_FFB1;
  readonly normalizesWeight = true;

  // FFB3 is physically an indicate characteristic, but the shared subscribe loop
  // only auto-subscribes bindings of type 'notify'. node-ble/noble enable
  // indications transparently from the char's real properties, so declare it
  // 'notify' to get it subscribed (same pattern as BeurerBf720).
  // Order matches the app capture: it enables FFB3 (indicate) before FFB2
  // (notify), and the scale's very first ack (the A1 "ready" indicate) arrives
  // right after FFB3 is armed, before FFB2 is even subscribed.
  readonly characteristics: CharacteristicBinding[] = [
    { uuid: CHR_FFB1, type: 'write' },
    { uuid: CHR_FFB3, type: 'notify' },
    { uuid: CHR_FFB2, type: 'notify' },
  ];

  private cachedWeight = 0;
  private cachedImpedance = 0;
  private cachedHeartRate = 0;
  private final = false;

  matches(device: BleDeviceInfo): boolean {
    const name = (device.localName || '').toLowerCase();
    // Swan/Icomon/YG are the openScale MGB protocol, not this one.
    if (name.startsWith('swan') || name === 'icomon' || name === 'yg') return false;
    if (name.includes('robi')) return true;

    // Hutbit units expose an (unused) FFB3 too, and their local name does not
    // survive every transport (the ESPHome proxy delivers an empty name), so the
    // swan-name guard above cannot catch a rebranded Hutbit here. Bow out of the
    // Lefu OEM advertisement fingerprint before claiming nameless FFB0 (#278);
    // otherwise this adapter wins post-discovery re-resolution and replays a
    // handshake the Hutbit rejects. This MUST be the same predicate the Hutbit
    // claims on: bowing out of a wider set than the Hutbit takes would strand
    // the device on MGB, which cannot parse this family's frames.
    if (isHutbitOemAdvert(device)) return false;

    // Nameless: require the FFB0 vendor service AND the FFB3 result characteristic
    // (post-discovery) to disambiguate from MGB scales, which expose FFB1/FFB2
    // but not the FFB3 indicate result char.
    const uuids = (device.serviceUuids || []).map((u) => u.toLowerCase());
    const hasFfb0 = uuids.some((u) => u === 'ffb0' || u === uuid16(0xffb0));
    const chars = (device.characteristicUuids || []).map((u) => u.toLowerCase());
    const hasFfb3 = chars.some((u) => u === 'ffb3' || u === CHR_FFB3);
    return hasFfb0 && hasFfb3;
  }

  /**
   * Clear the previous weigh-in before anything is subscribed (#394).
   *
   * This used to live in `onConnected`, which is too late for a multi-char
   * adapter: `subscribeAndInit` enables EVERY notify binding and only then
   * awaits `startInit()`, so frames can already be arriving - through several
   * D-Bus round trips for the second and third binding - while the reset has
   * not run. `onSessionStart` runs before the first subscribe.
   */
  onSessionStart(): void {
    this.cachedWeight = 0;
    this.cachedImpedance = 0;
    this.cachedHeartRate = 0;
    this.final = false;
  }

  async onConnected(ctx: ConnectionContext): Promise<void> {
    for (const frame of buildHandshake()) {
      bleLog.debug(`Robi S9 handshake write: ${frame.toString('hex')}`);
      await ctx.write(CHR_FFB1, frame, true);
      await new Promise((r) => setTimeout(r, 150));
    }
    bleLog.debug('Robi S9: handshake sent');
  }

  /**
   * A session that dies before `onConnected()` (e.g. a dropped subscribe)
   * leaves the previous reading cached, so the next connection's first
   * notification gets reported as a fresh result. So, reset here too.
   */
  onSessionEnd(): void {
    this.onSessionStart();
  }

  parseCharNotification(_charUuid: string, data: Buffer): ScaleReading | null {
    if (data.length < 11 || data[2] !== 0x00) return null;
    bleLog.debug(`Robi S9 frame: ${data.toString('hex')}`);

    // Final result arrives as the A3 frame on FFB3. A2 (live) frames use a
    // different alignment and are treated as progress only. A3 layout:
    //   [seq][len][00][a3][flag][weight u24 BE grams][... trailer]
    if (data[3] === 0xa3) {
      const w = data.readUIntBE(WEIGHT_OFFSET, WEIGHT_BYTES) / WEIGHT_DIV;
      if (w > 0 && Number.isFinite(w)) {
        this.cachedWeight = w;
        // Decoded from the app capture:
        // byte 8 = heart rate bpm,
        // bytes 9-10 = impedance ohm (both big-endian).
        // Guarded to a plausible physiological range so a handshake that
        // still comes back all-zero (the #248 symptom) yields 0 -> BIA fallback.
        const hr = data[8];
        const imp = data.readUInt16BE(9);
        this.cachedHeartRate = hr >= 30 && hr <= 220 ? hr : 0;
        this.cachedImpedance = imp >= 150 && imp <= 1200 ? imp : 0;
        this.final = true;
      }
    }

    if (this.final && this.cachedWeight > 0) {
      return { weight: this.cachedWeight, impedance: this.cachedImpedance };
    }
    return null;
  }

  /** Legacy single-char path (unused in multi-char mode, kept for the interface). */
  parseNotification(data: Buffer): ScaleReading | null {
    return this.parseCharNotification(CHR_FFB2, data);
  }

  isComplete(reading: ScaleReading): boolean {
    return reading.weight > 0 && this.final;
  }

  computeMetrics(reading: ScaleReading, profile: UserProfile): BodyComposition {
    // NOT BIA, despite what this comment used to say. `parseCharNotification`
    // emits `impedance: 0` on purpose: the only captured A3 frame has all-zero
    // bytes after the weight, so there is no impedance offset to read yet
    // (#248). The vendor's own body-comp frames are scrambled and not decoded
    // either, so body composition here is the Deurenberg BMI estimate and will
    // stay that way until someone posts a capture with a known impedance.
    //
    // Listed in #386 as an adapter that reads an impedance and ignores it. It
    // does not read one.
    return buildPayload(reading.weight, reading.impedance, {}, profile);
  }
}
